#!/sbin/openrc-run

name=$RC_SVCNAME
description="mbox service"
supervisor="supervise-daemon"
command="/usr/bin/mbox"
extra_commands="checkconfig"
extra_started_commands="reload"

: ${MBOX_CONFIG:=${config:-"/etc/mbox"}}

if [ -d "$MBOX_CONFIG" ]; then
	_config_opt="-C $MBOX_CONFIG"
elif [ -z "$MBOX_CONFIG" ]; then
	_config_opt=""
else
	_config_opt="-c $MBOX_CONFIG"
fi

_workdir=${MBOX_WORKDIR:-${workdir:-"/var/lib/mbox"}}

command_args="run --disable-color
	-D $_workdir
	$_config_opt"

depend() {
	after net dns
}

checkconfig() {
	ebegin "Checking $RC_SVCNAME configuration"
	mbox check -D "$_workdir" $_config_opt
	eend $?
}

start_pre() {
	checkconfig
}

reload() {
	ebegin "Reloading $RC_SVCNAME"
	checkconfig && $supervisor "$RC_SVCNAME" --signal HUP
	eend $?
}
